language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database alexs_beautiful_project;' -U postgres

before_install:
  - go get github.com/openshift/source-to-image/cmd/s2i

install:
  # - pip install -r requirements/local.txt
# command to run tests
script: 
  # - py.test --cov

after_success:
  - ./after_success.sh
