language: python
sudo: required
python:
  - "3.6"

services:
  - postgresql
  - docker

before_script:
  - psql -c 'create database alexs_beautiful_project;' -U postgres

before_install: ./before_install.sh
  - go get github.com/openshift/source-to-image/cmd/s2i

install: ./install.sh

script: ./script.sh

after_success:
  - ./after_success.sh

before_deploy: kubectl set image deployment/alexs_beautiful_project alexs_beautiful_project=us.gcr.io/alexs_beautiful_project/alexs_beautiful_project:$TRAVIS_TAG
