language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database alexs_beautiful_project;' -U postgres


install:
  - pip install -r requirements/local.txt
# command to run tests
script: pytest

after_success:
  - coveralls
